const $=id=>document.getElementById(id);
const load=$('load'),levelEl=$('level'),fpsEl=$('fps'),frameEl=$('frameTime'),workEl=$('workload'),stabilityEl=$('stability'),start=$('start'),benchmark=$('benchmark'),stop=$('stop'),statusEl=$('status'),sceneText=$('sceneText'),scene=$('scene'),dial=$('dialCanvas'),dc=dial.getContext('2d'),canvas=$('stressCanvas'),ctx=canvas.getContext('2d'),peakEl=$('peakLevel'),maxStableEl=$('maxStable'),bestEl=$('bestFps'),droppedEl=$('dropped'),scoreEl=$('score'),dialWrap=$('dialWrap');
let running=false,raf=0,last=0,frames=0,windowStart=0,particles=[],peak=0,bestFps=0,samples=[],frameTimes=[],dragging=false,benchmarking=false,benchStart=0,benchLevel=1,levelFps=[],expectedFrames=0,droppedFrames=0;
function size(){const r=scene.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);canvas.width=Math.max(1,r.width*d);canvas.height=Math.max(1,r.height*d);ctx.setTransform(d,0,0,d,0,0)}
function level(){return +load.value} function setLevel(v){v=Math.max(0,Math.min(10,Math.round(v)));load.value=v;levelEl.textContent=v;workEl.textContent=v*10+'%';drawDial();if(running)build()}
function angleToLevel(e){const r=dial.getBoundingClientRect(),x=e.clientX-r.left-r.width/2,y=e.clientY-r.top-r.height/2;let a=Math.atan2(y,x)+Math.PI/2;if(a<0)a+=Math.PI*2;return a/(Math.PI*2)*10}
function drawDial(){const w=dial.width,h=dial.height,cx=w/2,cy=h/2,r=132,n=level();dc.clearRect(0,0,w,h);dc.lineCap='round';dc.lineWidth=20;dc.strokeStyle='rgba(255,255,255,.07)';dc.beginPath();dc.arc(cx,cy,r,0,Math.PI*2);dc.stroke();if(n){const g=dc.createLinearGradient(35,35,325,325);g.addColorStop(0,'#b08cff');g.addColorStop(.5,'#78ddff');g.addColorStop(1,'#fff');dc.strokeStyle=g;dc.beginPath();dc.arc(cx,cy,r,-Math.PI/2,-Math.PI/2+Math.PI*2*n/10);dc.stroke()}for(let i=0;i<10;i++){const a=-Math.PI/2+i*Math.PI*2/10;dc.lineWidth=2;dc.strokeStyle=i<n?'rgba(190,160,255,.8)':'rgba(255,255,255,.14)';dc.beginPath();dc.moveTo(cx+147*Math.cos(a),cy+147*Math.sin(a));dc.lineTo(cx+157*Math.cos(a),cy+157*Math.sin(a));dc.stroke()}}
function build(){const n=180+level()*950;particles=Array.from({length:n},()=>({x:Math.random()*scene.clientWidth,y:Math.random()*scene.clientHeight,vx:(Math.random()-.5)*(1+level()*.6),vy:(Math.random()-.5)*(1+level()*.6),r:Math.random()*2.5+.4,a:Math.random()*6.28}))}
function cpuWork(lvl){let v=0;const loops=lvl*11000;for(let i=0;i<loops;i++)v+=Math.sin(i*.013)*Math.cos(i*.007)+Math.sqrt((i%97)+1);return v}
function render(t){if(!running)return;const dt=Math.min(80,t-last);last=t;frames++;expectedFrames+=Math.max(1,dt/16.67);const lvl=level(),w=scene.clientWidth,h=scene.clientHeight;ctx.fillStyle='rgba(3,4,9,.22)';ctx.fillRect(0,0,w,h);const intensity=1+lvl*.04;for(let i=0;i<particles.length;i++){const p=particles[i];p.x+=p.vx*(dt/16)*intensity;p.y+=p.vy*(dt/16)*intensity;p.a+=.015+lvl*.002;if(p.x<0||p.x>w)p.vx*=-1;if(p.y<0||p.y>h)p.vy*=-1;const rr=p.r*(1+lvl*.12)+Math.sin(p.a)*.5;const g=ctx.createRadialGradient(p.x,p.y,0,p.x,p.y,rr*7);g.addColorStop(0,'rgba(220,200,255,.95)');g.addColorStop(.25,'rgba(100,220,255,.35)');g.addColorStop(1,'rgba(80,210,255,0)');ctx.fillStyle=g;ctx.beginPath();ctx.arc(p.x,p.y,rr,0,Math.PI*2);ctx.fill()}if(lvl>=3)cpuWork(lvl);frameTimes.push(dt);if(t-windowStart>=600){const fps=Math.round(frames*1000/(t-windowStart));fpsEl.textContent=fps;bestFps=Math.max(bestFps,fps);bestEl.textContent=bestFps;const stability=Math.max(0,Math.min(100,Math.round(fps/60*100)));stabilityEl.textContent=stability+'%';samples.push(fps);if(benchmarking)levelFps.push({level:lvl,fps});if(window.LAGLAB_DASH?.push)window.LAGLAB_DASH.push(fps,dt);if(window.LAGLAB_UI?.live)window.LAGLAB_UI.live(fps,dt,lvl);frames=0;windowStart=t}frameEl.textContent=dt.toFixed(1)+' ms';peak=Math.max(peak,lvl);peakEl.textContent=peak;sceneText.textContent=benchmarking?'AUTO BENCHMARK • LEVEL '+lvl+'/10':'STRESS LEVEL '+lvl+'/10';if(benchmarking&&window.LAGLAB_UI){const pct=Math.min(100,(t-benchStart)/110);window.LAGLAB_UI.progress(pct,'LEVEL '+lvl+' / 10')}raf=requestAnimationFrame(render)}
function startTest(){if(running)return;window.LAGLAB_UI?.hideResult();benchmarking=false;running=true;peak=level();bestFps=0;samples=[];frameTimes=[];expectedFrames=0;droppedFrames=0;statusEl.textContent='RUNNING';start.disabled=true;benchmark.disabled=true;stop.disabled=false;build();last=performance.now();windowStart=last;frames=0;render(last)}
function startBenchmark(){if(running)return;window.LAGLAB_UI?.hideResult();benchmarking=true;benchStart=performance.now();benchLevel=1;levelFps=[];peak=0;bestFps=0;samples=[];frameTimes=[];expectedFrames=0;droppedFrames=0;maxStableEl.textContent='—';droppedEl.textContent='—';scoreEl.textContent='—';window.LAGLAB_UI?.progress(0,'LEVEL 1 / 10');setLevel(1);running=true;statusEl.textContent='BENCHMARK';start.disabled=true;benchmark.disabled=true;stop.disabled=false;build();last=performance.now();windowStart=last;frames=0;sceneText.textContent='AUTO BENCHMARK • LEVEL 1/10';render(last);requestAnimationFrame(benchmarkStep)}
function benchmarkStep(){if(!running||!benchmarking)return;const now=performance.now();if(now-benchStart>=11000){finishBenchmark();return}const elapsed=now-benchStart,target=Math.min(10,1+Math.floor(elapsed/1000));if(target!==benchLevel){if(levelFps.length){const recent=levelFps.filter(x=>x.level===benchLevel).map(x=>x.fps);const avg=recent.length?recent.reduce((a,b)=>a+b,0)/recent.length:0;if(avg>=30)maxStableEl.textContent=benchLevel;else{finishBenchmark();return}}benchLevel=target;setLevel(target)}requestAnimationFrame(benchmarkStep)}
function finishBenchmark(){const good=levelFps.filter(x=>x.fps>=30),stable=good.length?Math.max(...good.map(x=>x.level)):0;maxStableEl.textContent=stable;const avg=samples.length?samples.reduce((a,b)=>a+b,0)/samples.length:0;const sorted=frameTimes.length?[...frameTimes].sort((a,b)=>a-b):[];const p95=sorted.length?sorted[Math.min(sorted.length-1,Math.floor(sorted.length*.95))]:0;const longFrames=frameTimes.filter(dt=>dt>33).length;const dropPct=Math.min(100,Math.round((longFrames/Math.max(1,frameTimes.length))*100));droppedFrames=longFrames;droppedEl.textContent=dropPct+'%';const perf=Math.max(0,Math.min(100,Math.round(avg+stable*4+(p95&&p95<22?20:0))));const grade=perf>=90?'A':perf>=80?'B':perf>=65?'C':perf>=50?'D':'E';scoreEl.textContent=grade+' • '+perf+'/100';window.LAGLAB_UI?.progress(100,'COMPLETE');window.LAGLAB_HISTORY?.save({grade,score:perf+'/100',stable,fps:bestFps,dropped:dropPct});window.LAGLAB_UI?.showResult({grade,perf,stable,fps:bestFps,drop:dropPct,p95});stopTest(false)}
function stopTest(reset=true){if(!running)return;running=false;cancelAnimationFrame(raf);statusEl.textContent='READY';start.disabled=false;benchmark.disabled=false;stop.disabled=true;window.LAGLAB_UI?.idle();if(reset){const avg=samples.length?samples.reduce((a,b)=>a+b,0)/samples.length:0;const score=Math.max(0,Math.min(100,Math.round((avg/60)*70+peak*3)));scoreEl.textContent=score?score+'/100':'—';sceneText.textContent='READY FOR TEST';window.LAGLAB_UI?.progress(0,'READY')}else sceneText.textContent='BENCHMARK COMPLETE';ctx.clearRect(0,0,canvas.width,canvas.height);fpsEl.textContent='—';frameEl.textContent='—';stabilityEl.textContent='—'}
function pointerDown(e){if(benchmarking)return;dragging=true;dialWrap.setPointerCapture?.(e.pointerId);setLevel(angleToLevel(e))}function pointerMove(e){if(dragging)setLevel(angleToLevel(e))}function pointerUp(){dragging=false}
dialWrap.addEventListener('pointerdown',pointerDown);dialWrap.addEventListener('pointermove',pointerMove);dialWrap.addEventListener('pointerup',pointerUp);dialWrap.addEventListener('pointercancel',pointerUp);load.addEventListener('input',()=>{if(!benchmarking)setLevel(load.value)});start.addEventListener('click',startTest);benchmark.addEventListener('click',startBenchmark);stop.addEventListener('click',()=>stopTest(true));window.addEventListener('resize',size);window.addEventListener('pagehide',()=>stopTest(true));document.addEventListener('visibilitychange',()=>{if(document.hidden)stopTest(true)});size();drawDial();setLevel(0);peakEl.textContent='—';maxStableEl.textContent='—';bestEl.textContent='—';droppedEl.textContent='—';scoreEl.textContent='—';