const $=id=>document.getElementById(id);
const load=$('load'),levelEl=$('level'),fpsEl=$('fps'),frameEl=$('frameTime'),workEl=$('workload'),stabilityEl=$('stability'),start=$('start'),stop=$('stop'),statusEl=$('status'),sceneText=$('sceneText'),scene=$('scene'),dial=$('dialCanvas'),dc=dial.getContext('2d'),canvas=$('stressCanvas'),ctx=canvas.getContext('2d'),peakEl=$('peakLevel'),bestEl=$('bestFps'),scoreEl=$('score'),dialWrap=$('dialWrap');
let running=false,raf=0,last=0,frames=0,windowStart=0,particles=[],peak=0,bestFps=0,samples=[],dragging=false;
function size(){const r=scene.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);canvas.width=Math.max(1,r.width*d);canvas.height=Math.max(1,r.height*d);ctx.setTransform(d,0,0,d,0,0)}
function level(){return +load.value}
function setLevel(v){v=Math.max(0,Math.min(10,Math.round(v)));load.value=v;levelEl.textContent=v;workEl.textContent=v*10+'%';drawDial();if(running)build()}
function angleToLevel(e){const r=dial.getBoundingClientRect(),x=e.clientX-r.left-r.width/2,y=e.clientY-r.top-r.height/2;let a=Math.atan2(y,x)+Math.PI/2;if(a<0)a+=Math.PI*2;return a/(Math.PI*2)*10}
function drawDial(){const w=dial.width,h=dial.height,cx=w/2,cy=h/2,r=132,n=level();dc.clearRect(0,0,w,h);dc.lineCap='round';dc.lineWidth=20;dc.strokeStyle='rgba(255,255,255,.07)';dc.beginPath();dc.arc(cx,cy,r,0,Math.PI*2);dc.stroke();if(n){const g=dc.createLinearGradient(35,35,325,325);g.addColorStop(0,'#b08cff');g.addColorStop(.5,'#78ddff');g.addColorStop(1,'#fff');dc.strokeStyle=g;dc.beginPath();dc.arc(cx,cy,r,-Math.PI/2,-Math.PI/2+Math.PI*2*n/10);dc.stroke()}for(let i=0;i<10;i++){const a=-Math.PI/2+i*Math.PI*2/10;dc.lineWidth=2;dc.strokeStyle=i<n?'rgba(190,160,255,.8)':'rgba(255,255,255,.14)';dc.beginPath();dc.moveTo(cx+147*Math.cos(a),cy+147*Math.sin(a));dc.lineTo(cx+157*Math.cos(a),cy+157*Math.sin(a));dc.stroke()}}
function build(){const n=180+level()*950;particles=Array.from({length:n},()=>({x:Math.random()*scene.clientWidth,y:Math.random()*scene.clientHeight,vx:(Math.random()-.5)*(1+level()*.6),vy:(Math.random()-.5)*(1+level()*.6),r:Math.random()*2.5+.4,a:Math.random()*6.28}))}
function cpuWork(lvl){let v=0;const loops=lvl*11000;for(let i=0;i<loops;i++)v+=Math.sin(i*.013)*Math.cos(i*.007)+Math.sqrt((i%97)+1);return v}
function render(t){if(!running)return;const dt=Math.min(80,t-last);last=t;frames++;const lvl=level(),w=scene.clientWidth,h=scene.clientHeight;ctx.fillStyle='rgba(3,4,9,.22)';ctx.fillRect(0,0,w,h);const intensity=1+lvl*.04;for(let i=0;i<particles.length;i++){const p=particles[i];p.x+=p.vx*(dt/16)*intensity;p.y+=p.vy*(dt/16)*intensity;p.a+=.015+lvl*.002;if(p.x<0||p.x>w)p.vx*=-1;if(p.y<0||p.y>h)p.vy*=-1;const rr=p.r*(1+lvl*.12)+Math.sin(p.a)*.5;const g=ctx.createRadialGradient(p.x,p.y,0,p.x,p.y,rr*7);g.addColorStop(0,'rgba(220,200,255,.95)');g.addColorStop(.25,'rgba(100,220,255,.35)');g.addColorStop(1,'rgba(80,210,255,0)');ctx.fillStyle=g;ctx.beginPath();ctx.arc(p.x,p.y,rr,0,Math.PI*2);ctx.fill()}if(lvl>=3)cpuWork(lvl);if(t-windowStart>=600){fps=Math.round(frames*1000/(t-windowStart));fpsEl.textContent=fps;bestFps=Math.max(bestFps,fps);bestEl.textContent=bestFps;const stability=Math.max(0,Math.min(100,Math.round(fps/60*100)));stabilityEl.textContent=stability+'%';samples.push(fps);frames=0;windowStart=t}frameEl.textContent=dt.toFixed(1)+' ms';peak=Math.max(peak,lvl);peakEl.textContent=peak;sceneText.textContent='STRESS LEVEL '+lvl+'/10';raf=requestAnimationFrame(render)}
function startTest(){if(running)return;running=true;peak=level();bestFps=0;samples=[];statusEl.textContent='RUNNING';start.disabled=true;stop.disabled=false;build();last=performance.now();windowStart=last;frames=0;render(last)}
function stopTest(){if(!running)return;running=false;cancelAnimationFrame(raf);statusEl.textContent='READY';start.disabled=false;stop.disabled=true;const avg=samples.length?samples.reduce((a,b)=>a+b,0)/samples.length:0;const score=Math.max(0,Math.min(100,Math.round((avg/60)*70+peak*3)));scoreEl.textContent=score?score+'/100':'—';ctx.clearRect(0,0,canvas.width,canvas.height);fpsEl.textContent='—';frameEl.textContent='—';stabilityEl.textContent='—';sceneText.textContent='READY FOR TEST'}
function pointerDown(e){dragging=true;dialWrap.setPointerCapture?.(e.pointerId);setLevel(angleToLevel(e))}function pointerMove(e){if(dragging)setLevel(angleToLevel(e))}function pointerUp(){dragging=false}
dialWrap.addEventListener('pointerdown',pointerDown);dialWrap.addEventListener('pointermove',pointerMove);dialWrap.addEventListener('pointerup',pointerUp);dialWrap.addEventListener('pointercancel',pointerUp);load.addEventListener('input',()=>setLevel(load.value));start.addEventListener('click',startTest);stop.addEventListener('click',stopTest);window.addEventListener('resize',size);window.addEventListener('pagehide',stopTest);document.addEventListener('visibilitychange',()=>{if(document.hidden)stopTest()});size();drawDial();setLevel(0);peakEl.textContent='—';bestEl.textContent='—';scoreEl.textContent='—';